# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     fir_Debug
#     fir_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 5.0


# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

RM=cmd /C del /F /Q

#
# Begin "fir_Debug" configuration
#

ifeq ($(MAKECMDGOALS),fir_Debug)

fir_Debug : ./Debug/fir.dxe 

./Debug/fir.doj :fir.c $(VDSP)/21k/include/stdlib.h $(VDSP)/21k/include/stdio.h $(VDSP)/21k/include/stdio_21xxx.h 
	@echo ".\fir.c"
	$(VDSP)/cc21k.exe -c .\fir.c -file-attr ProjectName=fir -g -structs-do-not-overlap -no-multiline -double-size-32 -warn-protos -proc ADSP-21062 -o .\Debug\fir.doj -MM

./Debug/fir.dxe :$(VDSP)/21k/ldf/ADSP-21062.LDF $(VDSP)/21k/lib/060_hdr.doj ./Debug/fir.doj $(VDSP)/21k/lib/libc.dlb $(VDSP)/21k/lib/libdsp.dlb $(VDSP)/21k/lib/libio.dlb $(VDSP)/21k/lib/libcpp.dlb $(VDSP)/21k/lib/libeh.dlb $(VDSP)/21k/lib/libcpprt.dlb 
	@echo "Linking..."
	$(VDSP)/cc21k.exe .\Debug\fir.doj -L .\Debug -add-debug-libpaths -flags-link -od,.\Debug -o .\Debug\fir.dxe -proc ADSP-21062 -MM

endif

ifeq ($(MAKECMDGOALS),fir_Debug_clean)

fir_Debug_clean:
	-$(RM) ".\Debug\fir.doj"
	-$(RM) ".\Debug\fir.dxe"
	-$(RM) ".\Debug\*.ipa"
	-$(RM) ".\Debug\*.opa"
	-$(RM) ".\Debug\*.ti"
	-$(RM) ".\Debug\*.pgi"
	-$(RM) ".\*.rbld"

endif


